/* eslint-disable */
// Generated by tools/importer/check-images.mjs (bd-navigate-v1) on 2026-10-01T13:45:46.773Z. Do not edit.
// Content images that cannot be loaded on the source: dropped by the course cleanup transformer.
export default [
 "https://matrix-cms.unimelb.edu.au/?a=45131",
 "https://matrix-cms.unimelb.edu.au/__data/assets/image/0010/111421/KannanSethuraman.jpg",
 "https://matrix-cms.unimelb.edu.au/__data/assets/image/0017/420434/varieties/banner.jpg",
 "https://matrix-cms.unimelb.edu.au/__data/assets/image/0017/422306/varieties/banner.jpg",
 "https://matrix-cms.unimelb.edu.au/__data/assets/image/0028/46963/diploma-in-languages-banner.jpg",
 "https://matrix-cms.unimelb.edu.au/study-fac/content/courses-by-academic-division/graduate/fam/profiles/academic/Leon-de-Bruin-300px.jpg",
 "https://matrix-cms.unimelb.edu.au/study-fac/data/courses/grad/doctor-of-optometry/90b137e1ce72197f51a63df0f6652311992e66a6.png",
 "https://matrix-cms.unimelb.edu.au/study-fac/data/courses/grad/graduate-certificate-in-adolescent-health-and-wellbeing/iStock-1488889438.jpg",
 "https://matrix-cms.unimelb.edu.au/study-fac/data/courses/incompatible-courses/doctoral-program-in-economics/22180_0175.jpg/300x240.jpg",
 "https://matrix-cms.unimelb.edu.au/study-fac/data/courses/incompatible-courses/doctoral-program-in-economics/tim-robinso.jpg/300.jpg",
 "https://study.unimelb.edu.au/4024",
 "https://study.unimelb.edu.au/4732"
];
