/* eslint-disable */
// Generated by tools/importer/check-images.mjs (bd-navigate-v1) on 2026-10-01T04:41:06.293Z. Do not edit.
// Content images that cannot be loaded on the source: dropped by the course cleanup transformer.
export default [];
