/* eslint-disable */
/* global WebImporter */
/**
 * Parser for quote-profile. Base: quote (option: profile). Authored as "Quote (profile)".
 * Source: course-detail template, alumni profiles (career outcomes, student experience).
 *
 * Output (blocks/quote/README.md + quote.js `profile`): 1 row
 *   cell 1 (text) = <p>{caption, e.g. "Profile"}</p><h4>{name}</h4> + lower content:
 *                   paragraphs / lists; blockquote > p is authored as plain <p>, its <cite> pulled out
 *                   as a separate "— {cite}" attribution paragraph (inline links in the cite kept);
 *                   a YouTube/Vimeo iframe becomes a
 *                   link paragraph (videos inside alumni profiles are excluded from `video`).
 *   cell 2 (image) = portrait, only when it is not on the 403 list (never an empty image cell).
 * The "Read more" button is generated by quote.js (the source button is removed by cleanup).
 *
 * Source (verified in block-context/quote-profile/source.html + instances/01.html):
 *   div.toggleblock.alumniprofile >
 *     trigger: .alumniprofile__image .img (img or background-image), .alumniprofile__upper >
 *              strong.alumniprofile__caption, p.alumniprofile__name, button (removed)
 *     panel:   .alumniprofile__lower > div[.course-content] > p… | blockquote > p > cite | iframe
 */

const BLOCKED_IMAGES = [
  '/0018/48150/Physics.jpg',
  '/0014/41405/JG-YellowJacket-1098x780.png',
  '/0030/389019/varieties/thumb.jpg',
  '/0027/55449/accred_logos_accounting.jpg',
  '/0016/45124/',
  '/0022/45256/',
  '/0030/46875/study_banner_community.png',
];

function cleanText(el) {
  return (el ? el.textContent : '').replace(/\s+/g, ' ').trim();
}

function stripAttrs(root) {
  [root, ...root.querySelectorAll('*')].forEach((el) => {
    [...el.attributes].forEach((a) => {
      if (/^(style|class|id|tabindex|role|data-.*|aria-.*)$/i.test(a.name)) el.removeAttribute(a.name);
    });
  });
  return root;
}

function portrait(element, name, document) {
  const holder = element.querySelector('.alumniprofile__image .img, .alumniprofile__image');
  if (!holder) return null;
  const img = holder.querySelector('img');
  let src = img ? (img.getAttribute('src') || img.getAttribute('data-src') || '') : '';
  if (!src || /^(data|blob):/.test(src)) {
    const styled = [holder, ...holder.querySelectorAll('[style]')].find((el) => /url\(/.test(el.getAttribute('style') || ''));
    const m = styled && styled.getAttribute('style').match(/url\(\s*(['"]?)([^'")]+)\1\s*\)/i);
    src = m ? m[2].trim() : '';
  }
  if (!src || /^(data|blob):/.test(src)) return null;
  if (BLOCKED_IMAGES.some((frag) => src.includes(frag))) {
    console.warn(`[quote-profile] image dropped (403): ${src}`);
    return null;
  }
  const out = document.createElement('img');
  out.src = src;
  out.alt = (img && img.getAttribute('alt')) || name || '';
  return out;
}

function videoLink(iframe, document) {
  const src = iframe.getAttribute('src') || '';
  let href = '';
  const yt = src.match(/youtube(?:-nocookie)?\.com\/embed\/([^?&/"]+)/);
  const vm = src.match(/player\.vimeo\.com\/video\/(\d+)/);
  if (yt) href = `https://www.youtube.com/watch?v=${yt[1]}`;
  else if (vm) href = `https://vimeo.com/${vm[1]}`;
  else if (src) href = src;
  if (!href) return null;
  const a = document.createElement('a');
  a.href = href;
  a.textContent = (iframe.getAttribute('title') || '').trim() || href;
  const p = document.createElement('p');
  p.append(a);
  return p;
}

/** "— {cite}" paragraph, keeping inline links (e.g. a cite naming a linked profile). */
function attribution(cite, document) {
  const p = document.createElement('p');
  cite.querySelectorAll('br').forEach((b) => b.remove());
  p.append(...cite.childNodes);
  stripAttrs(p);
  const first = p.firstChild;
  if (first && first.nodeType === 3) first.textContent = first.textContent.replace(/^\s*[—–-]?\s*/, '');
  p.prepend('— ');
  return p;
}

/** Lower panel content -> paragraphs, quote + attribution, video links. */
function lowerContent(root, document) {
  const out = [];
  [...root.childNodes].forEach((n) => {
    if (n.nodeType === 3) {
      if (cleanText(n)) { const p = document.createElement('p'); p.textContent = cleanText(n); out.push(p); }
      return;
    }
    if (n.nodeType !== 1) return;
    if (n.tagName === 'IFRAME') { const v = videoLink(n, document); if (v) out.push(v); return; }
    if (n.tagName === 'BLOCKQUOTE') {
      const cites = [...n.querySelectorAll('cite')];
      cites.forEach((c) => c.remove());
      out.push(...lowerContent(n, document));
      cites.forEach((c) => {
        if (!cleanText(c)) return;
        out.push(attribution(c, document));
      });
      return;
    }
    if (/^(DIV|SECTION|SPAN)$/.test(n.tagName)) { out.push(...lowerContent(n, document)); return; }
    if (n.querySelector('iframe')) {
      n.querySelectorAll('iframe').forEach((f) => { const v = videoLink(f, document); f.remove(); if (v) out.push(v); });
    }
    if (n.tagName === 'P' && n.querySelector('cite')) {
      const cites = [...n.querySelectorAll('cite')];
      cites.forEach((c) => c.remove());
      if (cleanText(n)) out.push(stripAttrs(n));
      cites.forEach((c) => {
        if (!cleanText(c)) return;
        out.push(attribution(c, document));
      });
      return;
    }
    if (!cleanText(n) && !n.querySelector('img')) return;
    out.push(stripAttrs(n));
  });
  return out;
}

export default function parse(element, { document }) {
  const text = [];
  const caption = cleanText(element.querySelector('.alumniprofile__caption'));
  const name = cleanText(element.querySelector('.alumniprofile__name'));
  if (caption) { const p = document.createElement('p'); p.textContent = caption; text.push(p); }
  if (name) { const h4 = document.createElement('h4'); h4.textContent = name; text.push(h4); }

  // anything else in the upper area besides caption / name / button
  const upper = element.querySelector('.alumniprofile__upper');
  if (upper) {
    [...upper.children].forEach((c) => {
      if (c.matches('.alumniprofile__caption, .alumniprofile__name, button, .alumniprofile__trigger') || !cleanText(c)) return;
      text.push(stripAttrs(c));
    });
  }

  const lower = element.querySelector('.alumniprofile__lower')
    || element.querySelector('[data-testid="toggleblock-panel"]');
  if (lower) text.push(...lowerContent(lower, document));

  if (!text.length) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const image = portrait(element, name, document);
  const row = image ? [text, [image]] : [text];
  // `variants` keeps the option out of computeBlockName (header renders as "Quote (profile)").
  const block = WebImporter.Blocks.createBlock(document, { name: 'Quote', variants: ['profile'], cells: [row] });
  element.replaceWith(block);
}
